tables:
  - name: "employee"
    query: |
      CREATE TABLE public.employee (
         id VARCHAR,  -- Loaded as text by Airbyte
         name VARCHAR
      );
  - name: "department"
    query: |
      CREATE TABLE public.department (
         id VARCHAR,
         name VARCHAR
      );
