snowflake:
  user: "PARTHIV19"
  password: "@Kishan101101101"
  account: "YUXTTPP.OT86654"
  warehouse: "COMPUTE_WH"
  database: "DEMO"
  schema: "PUBLIC"

tables:
  - file: "tables/*.yaml"
views:
  - file: "views/*.yaml"
tasks:
  - file: "tasks/*.yaml"
snowpipes:
  - file: "snowpipes/*.yaml"

airbyte_connections:
  - name: "employee_connection"
    raw_schema: "raw"
    info_schema: "info"
    dbt:
      git_url: "https://github.com/yourorg/dbt-employee-models.git"
      branch: "main"
      models:
        - name: "employee_transform"
          raw_table: "employee"
          info_table: "employee_info"
          transformation: |
            SELECT 
              CAST(id AS INT) AS id, 
              UPPER(name) AS name, 
              CURRENT_TIMESTAMP() AS transformed_at
            FROM raw.employee
