tasks:
  - name: "employee_task"
    query: |
      CREATE TASK employee_task
      WAREHOUSE = COMPUTE_WH
      SCHEDULE = '1 MINUTE'
      AS
      INSERT INTO public.employee_view SELECT * FROM public.employee;
